-- public.api_restaurant definition

-- Drop table

DROP TABLE public.api_restaurant;

CREATE TABLE public.api_restaurant (
	id int4 NOT NULL,
	"name" varchar(100) NOT NULL,
	"location" varchar(30) NOT NULL,
	cuisine varchar(30) NOT NULL,
	rating float8 NOT NULL,
	contact_id int8 NULL,
	CONSTRAINT api_restaurant_contact_id_1f35d18b_uniq UNIQUE (contact_id),
	CONSTRAINT api_restaurant_name_e4dfb076_uniq UNIQUE (name),
	CONSTRAINT api_restaurant_pkey PRIMARY KEY (id),
	CONSTRAINT api_restaurant_contact_id_1f35d18b_fk_api_contact_id FOREIGN KEY (contact_id) REFERENCES public.api_contact(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX api_restaurant_name_e4dfb076_like ON public.api_restaurant USING btree (name varchar_pattern_ops);

INSERT INTO public.api_restaurant (id,name,"location",cuisine,rating,contact_id) VALUES
	 (1,'Pasta Paradise','Rome','Italian',4.5,1),
	 (2,'Curry King','Mumbai','Indian',4.7,5),
	 (3,'Sushi Suite','Tokyo','Japanese',4.9,6),
	 (4,'Taco T','Mexico City','Mexican',4.4,7),
	 (5,'Taco Bell','Mexico City','Mexican',4.7,11),
	 (6,'Taco Ring','Mexico City','Mexican',4.9,13);

-- public.api_contact definition

-- Drop table

DROP TABLE public.api_contact;

CREATE TABLE public.api_contact (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	phone varchar(15) NOT NULL,
	email varchar(254) NOT NULL,
	CONSTRAINT api_contact_pkey PRIMARY KEY (id)
);

 INSERT INTO public.api_contact (phone,email) VALUES
	 ('123-456-7890','info@pastaparadise.com'),
	 ('098-765-4321','contact@currykingdom.com'),
	 ('234-567-8901','reservations@sushisuite.com'),
	 ('345-678-9012','info@tacoterritory.mx'),
	 ('345-678-1290','info@tacobell.mx'),
	 ('345-678-1291','info@tacoring.mx');
